- nombre: Zapato 1
  precio: $0
  img: img/img_zap.jpg
  
- nombre: Zapato 2
  precio: $0
  img: img/img_zap.jpg
  
- nombre: Zapato 3
  precio: $0
  img: img/img_zap.jpg
  
- nombre: Zapato 4
  precio: $0
  img: img/img_zap.jpg

