- nombre: Zapato 1
  precio: $50
  img: img/img_zap.jpg
  
- nombre: Zapato 2
  precio: $5
  img: img/img_zap.jpg
  
- nombre: SUPER zapato
  precio: $10000
  img: img/img_zap.jpg
  
- nombre: Zapato de ciruja
  precio: $0.30
  img: img/img_zap.jpg

